# Вся документация есть на https://sw.kovidgoyal.net/kitty/conf/
# ~/.config/kitty/kitty.conf

# --- Шрифты ---
# Шрифты надо установить заблоговременно

font_size 14.0
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto


# --- Окно ---

# Вырубить дурацкий звук
enable_audio_bell no
# Сколько строк истории сохранять
scrollback_lines 5000
# Детектить URL
detect_urls yes
# Непрозрачность фона
background_opacity 0.9


# --- Визуал --- 

# Рамки окна в цвет фона
wayland_titlebar_color background


# Нижняя панель табов
# fade, slant, separator, powerline, custom
tab_bar_style slant

# Разделение окон

# Отступ от краев окна
window_margin_width 6
# Без отступов если окно одно
single_window_margin_width 0
# background_tint 0.9
# Нормальное поведение разделения
enabled_layouts Tall, *

# Открыть new split + cwd
map f1 new_window_with_cwd
