# Фон и текст
background #f5f0e7
foreground #000000  

# Курсор
cursor #000000
cursor_text_color #f5f0e7

# Выделение
selection_background #f2e5db
selection_foreground #000000

# Черно-белые
color0  #000000
color8  #555555

# Красные
color1  #d3694c
color9  #ff8e7a

# Зеленые
color2  #6a8f3b
color10 #8fba55

# Желтые
color3  #b58b2a
color11 #d6ac4b

# Синие
color4  #4a82b5
color12 #6fa6d8

# Пурпурные
color5  #955e96
color13 #b582b9

# Голубые/Циан
color6  #3c9992
color14 #62c4be

# Белые
color7  #e5e5e5
color15 #ffffff
